export const ROUTES = {
  auth: "/auth",
  dashboard: "/",
  compliance: "/compliance",
  safety: "/safety",
  location: "/location",
  assets: "/assets",
  maintenance: "/maintenance",
  eldEvents: "/eld-events",
  geofence: "/geofence",
  dispatch: "/dispatch",
  loads: "/loads",
  reports: "/reports",
  admin: "/admin",
  documents: "/documents",
  adminVehicles: "/admin/vehicles",
  adminTrailers: "/admin/trailers",
  adminCompany: "/admin/company",
};
